import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Toaster } from '@/components/ui/sonner'
import { Sidebar } from '@/components/nav/sidebar'
import { Navbar } from '@/components/nav/navbar'
import { ConfettiProvider } from '@/components/providers/confetti-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Note Share',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    <SessionProvider
      session={session}
    >
      <html lang="en">
        <body className={inter.className}>
            <main
            className='h-full'
            >
              <ConfettiProvider />
              {children}
              <Toaster
                position="bottom-right"
              />
            </main>
        </body>
      </html>
    </SessionProvider>
  )
}
