import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Toaster } from '@/components/ui/sonner'
import { Sidebar } from '@/components/nav/sidebar'
import { Navbar } from '@/components/nav/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Note Share',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    <SessionProvider
      session={session}
    >
      <html lang="en">
        <body className={inter.className}>
          <div
            className="h-full"
          >
            <div
              className="h-[80px] md:pl-56 fixed inset-y-0 w-full z-50"
            >
              <Navbar />
            </div>
            <div
              className=" hidden md:flex h-full w-56 flex-col fixed inset-y-0 z-50"
            >
              <Sidebar />
            </div>
            <main
              className="md:pl-56 pt-[80px] h-full"
            >
              {children}
              <Toaster
                position="bottom-right"
              />
            </main>
          </div>

        </body>
      </html>
    </SessionProvider>
  )
}
